apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: findmycar-api
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "0"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      containers:
      - image: gcr.io/findmycar-347ec/findmycar-api:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ENVIRONMENT
          value: "production"
        - name: DATABASE_URL
          value: "sqlite:///./findmycar.db"
        - name: LOG_LEVEL
          value: "INFO"
        - name: EBAY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: ebay-client-id
              key: latest
        - name: EBAY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: ebay-client-secret
              key: latest
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret-key
              key: latest
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "1"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
  traffic:
  - percent: 100
    latestRevision: true