# Cloud Build configuration for automatic deployment
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/findmycar-api:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/findmycar-api:latest',
      '-f', 'Dockerfile.cloudrun',
      '.'
    ]
    dir: 'findmycar'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/findmycar-api:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/findmycar-api:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'findmycar-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/findmycar-api:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - |
        ENVIRONMENT=production,
        ENABLE_SLOW_SOURCES=false
      - '--set-secrets'
      - |
        DATABASE_URL=database-url:latest,
        REDIS_URL=redis-url:latest,
        SECRET_KEY=secret-key:latest,
        EBAY_CLIENT_ID=ebay-client-id:latest,
        EBAY_CLIENT_SECRET=ebay-client-secret:latest

  # Deploy static files to Firebase Hosting
  - name: 'node:18'
    entrypoint: npm
    args: ['install', '-g', 'firebase-tools']

  - name: 'node:18'
    entrypoint: npx
    args: ['firebase', 'deploy', '--only', 'hosting', '--project', '$PROJECT_ID']
    dir: 'findmycar'

# Build configuration options
options:
  machineType: 'E2_HIGHCPU_8'
  timeout: '1200s'

# Store build logs
logsBucket: 'gs://$PROJECT_ID-cloudbuild-logs'

# Trigger configuration
# This file should be referenced in Cloud Build triggers